import { Metadata } from 'next'
import { Container } from '@/components/layout/containers'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Data Processing - Silent Scribe',
  description: 'Detailed information about how Silent Scribe processes your data through local-first architecture and minimal data collection practices.',
}

export default function DataProcessingPage() {
  return (
    <Container className="py-12 lg:py-20">
      <div className="mx-auto max-w-4xl">
        <div className="mb-8">
          <h1 className="text-4xl font-bold tracking-tight text-text-primary sm:text-5xl">
            Data Processing
          </h1>
          <p className="mt-4 text-xl text-text-secondary">
            Transparent information about how we handle your data
          </p>
        </div>

        <div className="prose prose-lg prose-slate max-w-none">
          {/* Overview */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Our Approach to Data Processing
            </h2>
            
            <p className="text-text-secondary mb-6">
              Silent Scribe is built on the principle of data minimization and local processing. This page provides 
              detailed, technical information about how we handle different types of data in our systems.
            </p>

            <div className="bg-green-50 border-l-4 border-green-400 p-4 my-6">
              <h3 className="text-green-800 font-medium mb-2">Core Principle</h3>
              <p className="text-green-800">
                <strong>Local-First Processing:</strong> Your writing, code, and documents are processed entirely on your local device. 
                We never see, store, or analyze your content.
              </p>
            </div>
          </section>

          {/* Content Processing */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Content Processing (Local Only)
            </h2>
            
            <h3 className="text-xl font-medium text-text-primary mb-3">
              Writing Assistant Processing
            </h3>
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-6">
              <h4 className="font-medium text-blue-900 mb-3">What Happens Locally</h4>
              <ul className="text-blue-800 space-y-2 text-sm">
                <li>• <strong>Text Analysis:</strong> Grammar, style, and clarity checking happens in your device's memory</li>
                <li>• <strong>Rule Engine:</strong> Style guide enforcement runs locally using embedded rule sets</li>
                <li>• <strong>Terminology Checking:</strong> Custom dictionaries and terminology lists stored and processed locally</li>
                <li>• <strong>Context Understanding:</strong> Code awareness and technical writing analysis performed on-device</li>
                <li>• <strong>Suggestions:</strong> All writing recommendations generated by local AI models</li>
              </ul>
            </div>

            <h3 className="text-xl font-medium text-text-primary mb-3">
              Technical Implementation
            </h3>
            <div className="space-y-4">
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Processing Location</h4>
                <p className="text-text-secondary text-sm">
                  All content analysis happens in your computer's RAM. Text is never written to temporary files, 
                  logs, or persistent storage during processing.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Data Flow</h4>
                <p className="text-text-secondary text-sm">
                  Your IDE → Silent Scribe Extension → Local NLP Engine → Suggestions back to IDE. 
                  No network requests or external API calls for content analysis.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Memory Management</h4>
                <p className="text-text-secondary text-sm">
                  Processing memory is automatically cleared after analysis. No content persists in memory 
                  beyond the immediate processing session.
                </p>
              </div>
            </div>

            <h3 className="text-xl font-medium text-text-primary mb-3 mt-6">
              What We Never Process Remotely
            </h3>
            <ul className="list-disc list-inside text-text-secondary mb-6 space-y-2">
              <li>Document content, text, or any writing you're working on</li>
              <li>Code snippets, comments, or technical documentation</li>
              <li>API keys, passwords, or sensitive strings in your files</li>
              <li>File names, paths, or project structure information</li>
              <li>Custom terminology, dictionaries, or style configurations</li>
              <li>Writing patterns, corrections, or usage statistics</li>
            </ul>
          </section>

          {/* Website Data Processing */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibent text-text-primary mb-4">
              Website Data Processing
            </h2>
            
            <h3 className="text-xl font-medium text-text-primary mb-3">
              Beta Signup Information
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-300 text-sm">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-3 py-2 text-left">Data Type</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Processing Purpose</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Legal Basis</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Retention</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Email Address</td>
                    <td className="border border-gray-300 px-3 py-2">Beta communication, updates, early access delivery</td>
                    <td className="border border-gray-300 px-3 py-2">Consent</td>
                    <td className="border border-gray-300 px-3 py-2">Until unsubscribe + 30 days</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">GitHub Username</td>
                    <td className="border border-gray-300 px-3 py-2">Understanding development context, optional</td>
                    <td className="border border-gray-300 px-3 py-2">Legitimate Interest</td>
                    <td className="border border-gray-300 px-3 py-2">Until program completion</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Tool Preferences</td>
                    <td className="border border-gray-300 px-3 py-2">Product development, feature prioritization</td>
                    <td className="border border-gray-300 px-3 py-2">Legitimate Interest</td>
                    <td className="border border-gray-300 px-3 py-2">Aggregated indefinitely</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Use Case Description</td>
                    <td className="border border-gray-300 px-3 py-2">Better beta experience, feature development</td>
                    <td className="border border-gray-300 px-3 py-2">Legitimate Interest</td>
                    <td className="border border-gray-300 px-3 py-2">Until program completion</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <h3 className="text-xl font-medium text-text-primary mb-3 mt-6">
              Data Processing Activities
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Collection</h4>
                <p className="text-text-secondary text-sm">
                  Data collected through web forms with explicit consent and clear purpose statements.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Storage</h4>
                <p className="text-text-secondary text-sm">
                  Encrypted storage in EU-based Supabase infrastructure with access controls and audit logging.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Processing</h4>
                <p className="text-text-secondary text-sm">
                  Automated email sending, manual review for product insights, aggregation for analytics.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Access</h4>
                <p className="text-text-secondary text-sm">
                  Limited to authorized team members on need-to-know basis with full audit trail.
                </p>
              </div>
            </div>
          </section>

          {/* Email Processing */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Email Processing and Automation
            </h2>
            
            <h3 className="text-xl font-medium text-text-primary mb-3">
              SendGrid Integration
            </h3>
            <p className="text-text-secondary mb-4">
              We use SendGrid as our email service provider to deliver beta program communications and updates.
            </p>
            
            <div className="space-y-4 mb-6">
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Data Shared with SendGrid</h4>
                <ul className="text-text-secondary text-sm space-y-1">
                  <li>• Email addresses for delivery purposes only</li>
                  <li>• First name (if provided) for personalization</li>
                  <li>• Email content and templates</li>
                  <li>• Delivery preferences and unsubscribe status</li>
                </ul>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">SendGrid's Role</h4>
                <ul className="text-text-secondary text-sm space-y-1">
                  <li>• Data Processor under GDPR (we remain Data Controller)</li>
                  <li>• Email delivery and bounce handling</li>
                  <li>• Basic engagement metrics (opens, clicks) - aggregated only</li>
                  <li>• Unsubscribe management and compliance</li>
                </ul>
              </div>
            </div>

            <h3 className="text-xl font-medium text-text-primary mb-3">
              Email Event Processing
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-300 text-sm">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-3 py-2 text-left">Event Type</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Data Collected</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Processing Purpose</th>
                    <th className="border border-gray-300 px-3 py-2 text-left">Individual Tracking</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Email Sent</td>
                    <td className="border border-gray-300 px-3 py-2">Timestamp, campaign ID</td>
                    <td className="border border-gray-300 px-3 py-2">Delivery confirmation</td>
                    <td className="border border-gray-300 px-3 py-2">No</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Email Opened</td>
                    <td className="border border-gray-300 px-3 py-2">Timestamp (aggregated)</td>
                    <td className="border border-gray-300 px-3 py-2">Campaign effectiveness</td>
                    <td className="border border-gray-300 px-3 py-2">No</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Link Clicked</td>
                    <td className="border border-gray-300 px-3 py-2">Link destination (aggregated)</td>
                    <td className="border border-gray-300 px-3 py-2">Content effectiveness</td>
                    <td className="border border-gray-300 px-3 py-2">No</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Unsubscribe</td>
                    <td className="border border-gray-300 px-3 py-2">Email address, timestamp</td>
                    <td className="border border-gray-300 px-3 py-2">Compliance, preference management</td>
                    <td className="border border-gray-300 px-3 py-2">Yes (required)</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-3 py-2">Bounce/Failure</td>
                    <td className="border border-gray-300 px-3 py-2">Email address, error type</td>
                    <td className="border border-gray-300 px-3 py-2">Delivery troubleshooting</td>
                    <td className="border border-gray-300 px-3 py-2">Temporary only</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          {/* Analytics Processing */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Website Analytics Processing
            </h2>
            
            <h3 className="text-xl font-medium text-text-primary mb-3">
              Plausible Analytics Implementation
            </h3>
            <p className="text-text-secondary mb-4">
              We use Plausible Analytics, a privacy-focused analytics platform that doesn't use cookies 
              or track individual users across sessions.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <h4 className="font-medium text-green-900 mb-2">What We Track</h4>
                <ul className="text-green-800 text-sm space-y-1">
                  <li>• Page views (anonymous)</li>
                  <li>• Referrer sources (which sites link to us)</li>
                  <li>• General geographic regions (country/state)</li>
                  <li>• Device categories (mobile/desktop)</li>
                  <li>• Popular content and user flows</li>
                </ul>
              </div>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <h4 className="font-medium text-blue-900 mb-2">What We Don't Track</h4>
                <ul className="text-blue-800 text-sm space-y-1">
                  <li>• Individual users or sessions</li>
                  <li>• Personal identifiers or IP addresses</li>
                  <li>• Cross-site tracking or cookies</li>
                  <li>• Detailed behavioral patterns</li>
                  <li>• Any personally identifiable information</li>
                </ul>
              </div>
            </div>

            <h3 className="text-xl font-medium text-text-primary mb-3">
              Analytics Data Processing
            </h3>
            <ul className="list-disc list-inside text-text-secondary mb-6 space-y-2">
              <li><strong>Collection Method:</strong> Lightweight JavaScript beacon with minimal data payload</li>
              <li><strong>Data Anonymization:</strong> IP addresses are immediately anonymized and not stored</li>
              <li><strong>Aggregation:</strong> All data is aggregated and cannot be traced back to individuals</li>
              <li><strong>Retention:</strong> Analytics data retained for 24 months for trend analysis</li>
              <li><strong>Access:</strong> Only aggregate reports accessible to authorized team members</li>
            </ul>
          </section>

          {/* Third-Party Processors */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Third-Party Data Processors
            </h2>
            
            <p className="text-text-secondary mb-6">
              We work with a minimal set of trusted service providers who act as data processors under GDPR. 
              All have appropriate data processing agreements and security measures in place.
            </p>

            <div className="space-y-6">
              <div className="border border-gray-200 rounded-lg p-6">
                <div className="flex items-center mb-4">
                  <h3 className="text-lg font-medium text-text-primary">Supabase</h3>
                  <span className="ml-3 px-2 py-1 bg-green-100 text-green-800 text-xs rounded">Database & Backend</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                  <div>
                    <strong className="text-text-primary">Data Processed:</strong>
                    <p className="text-text-secondary">Beta signup data, email preferences, account information</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Security Measures:</strong>
                    <p className="text-text-secondary">EU servers, encryption at rest/transit, SOC 2 Type II, GDPR compliant</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Data Location:</strong>
                    <p className="text-text-secondary">European Union (Frankfurt, Germany)</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Access Controls:</strong>
                    <p className="text-text-secondary">Role-based access, audit logging, MFA required</p>
                  </div>
                </div>
              </div>

              <div className="border border-gray-200 rounded-lg p-6">
                <div className="flex items-center mb-4">
                  <h3 className="text-lg font-medium text-text-primary">SendGrid</h3>
                  <span className="ml-3 px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded">Email Services</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                  <div>
                    <strong className="text-text-primary">Data Processed:</strong>
                    <p className="text-text-secondary">Email addresses, email content, delivery events</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Security Measures:</strong>
                    <p className="text-text-secondary">SOC 2 Type II, ISO 27001, encryption, DPA signed</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Data Location:</strong>
                    <p className="text-text-secondary">United States (Standard Contractual Clauses)</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Retention:</strong>
                    <p className="text-text-secondary">Email events retained for 30 days, addresses until unsubscribe</p>
                  </div>
                </div>
              </div>

              <div className="border border-gray-200 rounded-lg p-6">
                <div className="flex items-center mb-4">
                  <h3 className="text-lg font-medium text-text-primary">Plausible Analytics</h3>
                  <span className="ml-3 px-2 py-1 bg-purple-100 text-purple-800 text-xs rounded">Website Analytics</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                  <div>
                    <strong className="text-text-primary">Data Processed:</strong>
                    <p className="text-text-secondary">Anonymous page views, referrers, device categories</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Security Measures:</strong>
                    <p className="text-text-secondary">No cookies, no personal data, GDPR compliant by design</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Data Location:</strong>
                    <p className="text-text-secondary">European Union</p>
                  </div>
                  <div>
                    <strong className="text-text-primary">Privacy Features:</strong>
                    <p className="text-text-secondary">No cross-site tracking, no user profiles, aggregated data only</p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* User Rights */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Your Data Rights and Controls
            </h2>
            
            <h3 className="text-xl font-medium text-text-primary mb-3">
              GDPR Rights Implementation
            </h3>
            <div className="space-y-4">
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Right to Access (Article 15)</h4>
                <p className="text-text-secondary text-sm mb-2">
                  Request a complete copy of all personal data we hold about you.
                </p>
                <p className="text-text-secondary text-sm">
                  <strong>Implementation:</strong> Email data-export@silentscribe.dev with verification. 
                  Response within 30 days with structured data export.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Right to Rectification (Article 16)</h4>
                <p className="text-text-secondary text-sm mb-2">
                  Correct any inaccurate or incomplete personal data.
                </p>
                <p className="text-text-secondary text-sm">
                  <strong>Implementation:</strong> Email corrections to hello@silentscribe.dev. 
                  Updates processed within 48 hours.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Right to Erasure (Article 17)</h4>
                <p className="text-text-secondary text-sm mb-2">
                  Request complete deletion of your personal data from our systems.
                </p>
                <p className="text-text-secondary text-sm">
                  <strong>Implementation:</strong> One-click unsubscribe or email deletion request. 
                  Complete removal within 48 hours, confirmed via email.
                </p>
              </div>
              <div className="border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-text-primary mb-2">Right to Portability (Article 20)</h4>
                <p className="text-text-secondary text-sm mb-2">
                  Receive your data in machine-readable format for transfer to another service.
                </p>
                <p className="text-text-secondary text-sm">
                  <strong>Implementation:</strong> JSON export including all signup data, preferences, 
                  and communication history available on request.
                </p>
              </div>
            </div>

            <h3 className="text-xl font-medium text-text-primary mb-3 mt-6">
              Automated Processing and Decisions
            </h3>
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <h4 className="font-medium text-yellow-900 mb-2">No Automated Decision Making</h4>
              <p className="text-yellow-800 text-sm">
                Silent Scribe does not use automated decision-making or profiling that produces legal 
                effects or significantly affects individuals. All beta program decisions and communications 
                involve human review.
              </p>
            </div>
          </section>

          {/* Contact Information */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              Data Protection Contact
            </h2>
            
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
              <h3 className="text-lg font-medium text-text-primary mb-4">Data Protection Queries</h3>
              <div className="space-y-3">
                <div>
                  <strong className="text-text-primary">Data Protection Officer:</strong>
                  <span className="text-text-secondary ml-2">privacy@silentscribe.dev</span>
                </div>
                <div>
                  <strong className="text-text-primary">Data Requests:</strong>
                  <span className="text-text-secondary ml-2">data-export@silentscribe.dev</span>
                </div>
                <div>
                  <strong className="text-text-primary">General Privacy Questions:</strong>
                  <span className="text-text-secondary ml-2">hello@silentscribe.dev</span>
                </div>
                <div>
                  <strong className="text-text-primary">Response Time:</strong>
                  <span className="text-text-secondary ml-2">Within 30 days for formal requests, 48 hours for general queries</span>
                </div>
              </div>
            </div>

            <p className="text-text-secondary mt-6">
              For more information about our privacy practices, please see our 
              <Link href="/privacy" className="text-blue-600 hover:text-blue-800 ml-1">Privacy Policy</Link> and 
              <Link href="/security" className="text-blue-600 hover:text-blue-800 ml-1">Security</Link> pages.
            </p>
          </section>
        </div>
      </div>
    </Container>
  )
}
